### ISSUE TITLE
MD17 training problem

### ISSUE THREAD

**Issue by Frank-LIU-520** [klicperajo/dimenet#10]
In your paper, you tested the model on the harder task of using only 1000 training samples. How did you select those 1000 samples, by random sampling, the first appeared 1000 configurations in the time line or some sampling method to achieve this? What's more , how many samples did you used for validation and testing? Glad if you can help.

**Comment by gasteigerjo** [comment]
The samples were chosen randomly. We use 10,000 validation samples. If you use the same dataset you should get the exact same data split with:

```python
seed = 42
random_state = np.random.RandomState(seed=seed)
idx = random_state.permutation(np.arange(len(data)))
idx_train = idx[0:ntrain]
idx_valid = idx[ntrain:ntrain+nvalid]
idx_test  = idx[ntrain+nvalid:]
```
