### ISSUE TITLE
questions about qm9

### ISSUE THREAD

**Issue by xnuohz** [klicperajo/dimenet#11]
Hi, what do `id, N, Z, R` mean in `qm9_eV.npz`?
Thanks:)

**Comment by gasteigerjo** [comment]
`id` is a unique identifier for each molecule.
`R` are the coordinates of each atom.
`Z` is the atomic number.
`N` is the number of atoms in each molecule. Atomic properties like `Z` and `R` are just concatenated globally, so you need this value to select the correct atoms for each molecule.
