### ISSUE TITLE
How can we train dimenet on MD17? Any tutorial?

### ISSUE THREAD

**Issue by Frank-LIU-520** [klicperajo/dimenet#18]
Hi, Klicperajo, Guten Tag! I would like to reproduce your results on MD17 but can't find where do you obtain the derivatives of energies to obtain the forces in the codes. Can you give me some instructions? Thank you so much.

**Comment by gasteigerjo** [comment]
Guten Tag!

The MD17 code is indeed not included in this repository. Essentially, you need to make 2 changes for MD predictions:
1. Change `training/data_container.py` and `training/data_provider.py` to read the MD17 data and provide forces.
2. Compute the derivatives w.r.t. the positions to calculate the forces and then add this to the loss. I would recommend doing that in `training/trainer.py`. You can get the forces like this:
```python
with tf.GradientTape(watch_accessed_variables=False) as force_tape:
    force_tape.watch(inputs['R'])
    energy = self.model(inputs, training=training)
forces = - force_tape.gradient(energy, inputs['R'])
```
I hope this helps!
