### ISSUE TITLE
Are loss values scaled?

### ISSUE THREAD

**Issue by ghost** [klicperajo/dimenet#19]
While running DimeNet++ with the pretrained weights, I noticed that the MAE for certain targets seem to be scaled, for example:
* The reported test MAE (in the paper) for `homo` is 24.6, but the MAE reported by `predict.ipynb` is 0.0246.
* The reported test MAE (in the paper) for `zpve` is 1.21, but the MAE reported by `predict.ipynb` is 0.00121.

Am I correct in thinking that there is some scaling going on, and could you point me to where it occurs? (i.e. if it was done during featurization, reporting, or somewhere else) Thanks!

**Comment by gasteigerjo** [comment]
Thank you for your interest in our work!

Indeed, as the name `qm9_eV.npz` suggests, the values in the dataset are saved in eV, while the results in the paper are reported in meV, as noted in the table. We leave the choice of prefix to the user.
