### ISSUE TITLE
QM9

### ISSUE THREAD

**Issue by CODE-SUBMIT** [klicperajo/dimenet#2]
Dear

I follow the config.ymal and run the codes, however I only got logMAE -4.2913 for the test[QM9].

Is there some config to reproduce the logMAE in the paper.

**Comment by gasteigerjo** [comment]
I am not sure which target you are talking about and how you arrived at this. Please keep in mind that you always only train a single model for a single target in `train.ipynb`.

The code and config in this repository does reproduce (or even surpass) the MAE reported in the paper for 8/12 targets (after the required 3,000,000 training steps). We are currently investigating the 4 remaining targets to see why those MAEs seem to be around 30% worse in TensorFlow 2. (these are mu, HOMO, LUMO, and gap).

**Comment by gasteigerjo** [comment]
After 55332daf9a505827c70d07d204f2901a25dcc1ee the 4 remaining targets now also match the reported performance.
