### ISSUE TITLE
RBF / SBF Known Issue

### ISSUE THREAD

**Issue by ghost** [klicperajo/dimenet#20]
Hello, I saw the following mentioned in the known issues:

> The radial basis functions in the interaction block actually use d_kj and not d_ji. The best way to fix this is by just using d_ji instead of d_kj in the SBF and leaving the RBF unchanged (DimeNet and DimeNet++).

From comparing with the diagram of the model, I can understand the first sentence. However, I don't completely grasp the suggested fix (and why `interaction_pp_block.py:59` is highlighted) -- would you be able to explain the suggested fix a little bit further?

Thanks!

**Comment by gasteigerjo** [comment]
To "fix" this you just have to pass `id_reduce_ji` instead of `id_expand_kj` here: https://github.com/klicperajo/dimenet/blob/master/dimenet/model/dimenet_pp.py#L120
