### ISSUE TITLE
Detail property values in QM9

### ISSUE THREAD

**Issue by Nokimann** [klicperajo/dimenet#21]
Where did you obtain the [QM9](https://figshare.com/collections/Quantum_chemistry_structures_and_properties_of_134_kilo_molecules/978904) data?

For example, in qm9_eV.npz, 
the 1st data corresponds to CH4 in QM9.
And its U0, U, H, G are -17.172180532853258, -17.286822102173918, -17.389653929960044, -16.151916825255373 in eV(?), respectively.

In [QM9](https://figshare.com/collections/Quantum_chemistry_structures_and_properties_of_134_kilo_molecules/978904), U0, U, H, G are  -1101.487799054311, -1101.4097567985575, -1101.384042038555, -1102.0229653876108 in eV, respectively, which means neither eV unit nor Hartree unit matches with the qm9_eV.npz data.

Or was some preprocessing applied?

**Comment by gasteigerjo** [comment]
The version of QM9 in this repo contains the atomization energies in eV, not the full internal energy, which you are probably referring to.

**Comment by Nokimann** [comment]
Thank you @klicperajo

Completely understood.
