### ISSUE TITLE
Creation of Custom Dataset-OMDB

### ISSUE THREAD

**Issue by aydinmirac** [klicperajo/dimenet#22]
Dear All,

First of all, thank you for the effort to create this awesome model, Dimenet.

I have been working with SchNetpack to predict bandgap using OMDB(Open Material Database) dataset. It is quite similar to QM9. Xyz file that includes coordinates and csv file that includes bandgaps and so on. You can find the dataset below:

[https://omdb.mathub.io/dataset](url)

I am working with big molecules (consisting of around 140-150 atoms). that is why I am not able to use QM9 because my model does not give good result with small molecules in QM9. OMDB average is 82 atom per molecule.

I wonder how I can create custom dataset from OMDB to use DimeNet? Do you have any plan to implement other datasets? I saw QM9.npz file in the "data" folder but I am not sure how you have created it.

I appreciate your help.
Mirac

**Comment by gasteigerjo** [comment]
Dear Miraç,

Thank you for your interest in using DimeNet!

The data structure of these npz-files is quite straightforward. It's really just a few numpy arrays with the necessary data (atomic numbers, positions, molecule IDs, number of atoms per molecule). The atom information (atomic numbers, positions) of all molecules are concetanated into one long array, which is separated when reading by using the numbers of atoms per molecule.

You can inspect the provided dataset by loading it with `np.load(filename, allow_pickle=True)`, as done [here](https://github.com/klicperajo/dimenet/blob/master/dimenet/training/data_container.py#L10). You can save (create) a new dataset by calling `np.savez(filename, **data_dict)` with your data dictionary.

Furthermore, note that our models are trained on the atomization energy (for U0, U, G, and H), not the total inner energy.
