### ISSUE TITLE
How to plt the image

### ISSUE THREAD

**Issue by anny0316** [klicperajo/dimenet#25]
Hello, It is a great work. Thank you for the shared code. By the way, I want to know that how to plt the image  (https://github.com/gasteigerjo/dimenet/blob/master/2dfilters_large_layer2.png).  Thanks a lot.

**Comment by gasteigerjo** [comment]
These plots were created by loading the trained model, scanning over the angle and distance inputs and recording the resulting embeddings. The plots were then generated with matplotlib's polar projection and a pcolormesh.

**Comment by anny0316** [comment]
Thank you very much, can you share the codes about these plots?

**Comment by gasteigerjo** [comment]
I'm afraid I can't share that code. It's not well documented, uses deprecated APIs, and would not be helpful. It would be faster if you developed your own along the lines I've mentioned above.

**Comment by anny0316** [comment]
OK, Thank you.
