### ISSUE TITLE
Reimplementation in graph mode using TF1

### ISSUE THREAD

**Issue by Jagyan** [klicperajo/dimenet#26]
Hi, I am trying to implement the model in graph mode using tensorflow 1 and I am facing a problem which seems to be associated with the model's dependence on eager mode for calculating certain features. The getitem part of the data container receives the existing features in form of batch and process it as a batch to generate other fields which are variable shapes. However, in graph mode this is not feasible as data has to be of similar share for each data point. Do you see this possible using graph mode? If so, how do you suggest to implement this is graph mode.

**Comment by gasteigerjo** [comment]
First of all, I'm not sure why you are using a library that has been outdated for 3 years. Anyway, the data container is not meant to be run in graph mode. It runs in parallel on the CPU and is based on Numpy. The handover to TensorFlow and graph mode then happens in the data provider. You will have to adapt its `get_idx_dataset` and `idx_to_data_tf` functions for TF1.

By the way, this library already runs in TF2's graph execution mode by using `@tf.function`, which corresponds to TF1's graph mode.
