### ISSUE TITLE
The link to COLL dataset is not working

### ISSUE THREAD

**Issue by waqarahmed89** [klicperajo/dimenet#28]
Dear authors, the following link is not accessible. Any alternate link?

https://figshare.com/articles/dataset/COLL_Dataset_v1_2/13289165/1

**Comment by gasteigerjo** [comment]
Thank you for reaching out!

Both the link you shared and the [link on the project page](https://doi.org/10.6084/m9.figshare.13289165.v1) are accessible on my side, so I'm not sure what to fix here.
