### ISSUE TITLE
Coll dataset units

### ISSUE THREAD

**Issue by spozdn** [klicperajo/dimenet#29]
Dear authors,
Could you confirm that the units of the COLL dataset available here 
https://figshare.com/articles/dataset/COLL_Dataset_v1_2/13289165/1
are eV and eV/A for energies and forces, respectively (some readme would be really helpful :) )?

Also, could you confirm that the errors in forces reported in DimeNet and GemNet papers are per a single xyz component?

**Comment by gasteigerjo** [comment]
Hi Sergey!

Thank you for your interest!

The units in COLL are indeed eV and eV/A. Note that the atomization energy is the relevant one for prediction tasks.

The errors in DimNet and GemNet are mean absolute errors (MAEs), as defined e.g. in the second term of Equation 2 in the DimeNet (not DimeNet++) paper. You can also see this in the code [here](https://github.com/gasteigerjo/dimenet/blob/master/dimenet/training/trainer.py#L60-L66).

**Comment by spozdn** [comment]
Thanks!
