### ISSUE TITLE
each single target 

### ISSUE THREAD

**Issue by CODE-SUBMIT** [klicperajo/dimenet#3]

**Comment by CODE-SUBMIT** [comment]
Dear 

Thank you for good work and code.

Does it  mean I  run  train.ipynb 12 times to get the result of each single target.

**Comment by gasteigerjo** [comment]
Yes, exactly. You can also train one model for all targets (multi-target). We've also reported results for this setting, see Appendix E in the paper.

**Comment by Mario-Liu** [comment]
How long does it takes for one single task training and which GPU did you use in your training?
