### ISSUE TITLE
incorporating Dimenet++ intio Lammps

### ISSUE THREAD

**Issue by XinjianOUYANG** [klicperajo/dimenet#30]
Hi, I'm working on creating an interface between dimenet and Lammps to carry out molecular dynamics simulations, and it seems that I need to  convert the Dimenet code into a C++ version, which bothers me. I want to know if you have done similar works on this topic or could you provide some guidances to me?
Thanks a lot!

**Comment by gasteigerjo** [comment]
Hi!

Thank you for your interest in our work! Unfortunately, I have not done similar work and cannot help you with this project. Maybe there is some method for automatically converting a TensorFlow Keras model to C++.
