### ISSUE TITLE
Input issue

### ISSUE THREAD

**Issue by fatto6591** [klicperajo/dimenet#32]
hi , I wonder if dimenet can accept an input with more than one molecule . I am working on predicting reaction condiction , so i must input reactant and product at the same time

**Comment by gasteigerjo** [comment]
Technically, DimeNet just gets a point cloud as an input: Coordinates in spaces and types of atoms. So it can handle any arbitrary atomic configuration.

However, you need to make sure that your training data covers the kinds of configurations you're interested in. So if you want to predict reactions, you first need to train it on reaction data.
