### ISSUE TITLE
KeyError: 'ceil'

### ISSUE THREAD

**Issue by aksham-mahajan** [klicperajo/dimenet#5]
model = DimeNet(emb_size=emb_size, num_blocks=num_blocks, num_bilinear=num_bilinear,
                num_spherical=num_spherical, num_radial=num_radial,
                cutoff=cutoff, envelope_exponent=envelope_exponent,
                num_before_skip=num_before_skip, num_after_skip=num_after_skip,
                num_dense_output=num_dense_output, num_targets=len(targets),
                activation=swish)

When i try to run this i get the following error :

--------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)

<ipython-input-13-e2a12a7738ac> in <module>()
      4                 num_before_skip=num_before_skip, num_after_skip=num_after_skip,
      5                 num_dense_output=num_dense_output, num_targets=len(targets),
----> 6                 activation=swish)

4 frames

/content/drive/My Drive/dimenet/dimenet/model/dimenet.py in __init__(self, emb_size, num_blocks, num_bilinear, num_spherical, num_radial, cutoff, envelope_exponent, num_before_skip, num_after_skip, num_dense_output, num_targets, activation, name, **kwargs)
     55             num_radial, cutoff=cutoff, envelope_exponent=envelope_exponent)
     56         self.sbf_layer = SphericalBasisLayer(
---> 57             num_spherical, num_radial, cutoff=cutoff, envelope_exponent=envelope_exponent)
     58 
     59         # Embedding and first output block

/content/drive/My Drive/dimenet/dimenet/model/layers/spherical_basis_layer.py in __init__(self, num_spherical, num_radial, cutoff, envelope_exponent, name, **kwargs)
     30         for i in range(num_spherical):
     31             if i == 0:
---> 32                 first_sph = sym.lambdify([theta], self.sph_harm_formulas[i][0], 'tensorflow')(0)
     33                 self.sph_funcs.append(lambda tensor: tf.zeros_like(tensor) + first_sph)
     34             else:

/usr/local/lib/python3.6/dist-packages/sympy/utilities/lambdify.py in lambdify(args, expr, modules, printer, use_imps, dummify)
    377     namespace = {}
    378     for m in namespaces[::-1]:
--> 379         buf = _get_namespace(m)
    380         namespace.update(buf)
    381 

/usr/local/lib/python3.6/dist-packages/sympy/utilities/lambdify.py in _get_namespace(m)
    469     """
    470     if isinstance(m, str):
--> 471         _import(m)
    472         return MODULES[m][0]
    473     elif isinstance(m, dict):

/usr/local/lib/python3.6/dist-packages/sympy/utilities/lambdify.py in _import(module, reload)
    162     # Add translated names to namespace
    163     for sympyname, translation in translations.items():
--> 164         namespace[sympyname] = namespace[translation]
    165 
    166     # For computing the modulus of a sympy expression we use the builtin abs

KeyError: 'ceil'

I try this on colab and to solve the error need to update the scipy version to 1.5.

**Comment by gasteigerjo** [comment]
That's what you see when your `sympy` package is not up to date, you need to update it to 1.5. You say scipy in your post instead, which is certainly a typo. Scipy doesn't even have a 1.5 yet.
