### ISSUE TITLE
Request for a pretrained model

### ISSUE THREAD

**Issue by AnirudhDagar** [klicperajo/dimenet#6]
Hi @klicperajo 

As you mentioned the model takes around 20 days to train on a single GPU (a 1080Ti), it would be nice if you could share the pre-trained model so that one can easily run and restore the checkpoint to reproduce the results. Otherwise, 20 days of training is a long time.

Thanks :)

**Comment by gasteigerjo** [comment]
Yes, I can totally see that. We are planning to release a set of pretrained models in the next couple of days.

**Comment by gasteigerjo** [comment]
Pretrained models have been added in 34bfe28.
