### ISSUE TITLE
Recomputing rbf and sbf each pass could memoization/caching speed up code?

### ISSUE THREAD

**Issue by CompRhys** [klicperajo/dimenet#8]
is there any reason that you need to recompute the rbf and sbf features each pass through the model?

https://github.com/klicperajo/dimenet/blob/bf725c33755cd6fb87661fe03956b5fb30889742/dimenet/model/dimenet.py#L94

I haven't profiled the code so am not sure if this is significant but I would think that you could just pass Z, sbf and rbf as inputs to the model rather than Z and R?

**Comment by gasteigerjo** [comment]
During my profiling I didn't find this to be significant. Yes, you could precompute these, save them and input them to the model. But then you can't backpropagate to the atom coordinates to get the forces for molecular dynamics.

**Comment by CompRhys** [comment]
ahh forces!
